config/routes.rb
Rails.application.routes.draw do

  resources :front_pages

  root "front_pages#main"
end

app/models/front_page.rb
class FrontPage < ActiveRecord::Base
end

app/controllers/front_pages_controller.rb
class FrontPagesController < ApplicationController
  before_action :set_front_page, only: [:show, :edit, :update, :destroy]


  def randomScalingFactor
    return rand(0..100)
  end

  def main

    @horizontal_grouped_bar_array = [
          {
              key: 'Series1',
              values: [
                  {
                      label: "Group A" ,
                      value: -1.8746444827653
                  } ,
                  {
                      label: "Group B" ,
                      value: -8.0961543492239
                  } ,
                  {
                      label: "Group C" ,
                      value: -0.57072943117674
                  } ,
                  {
                      label: "Group D" ,
                      value: -2.4174010336624
                  } ,
                  {
                      label: "Group E" ,
                      value: -0.72009071426284
                  } ,
                  {
                      label: "Group F" ,
                      value: -2.77154485523777
                  } ,
                  {
                      label: "Group G" ,
                      value: -9.90152097798131
                  } ,
                  {
                      label: "Group H" ,
                      value: 14.91445417330854
                  } ,
                  {
                      label: "Group I" ,
                      value: -3.055746319141851
                  }
              ]
          },
          {
              key: 'Series2',
              values: [
                  {
                      label: "Group A" ,
                      value: 25.307646510375
                  } ,
                  {
                      label: "Group B" ,
                      value: 16.756779544553
                  } ,
                  {
                      label: "Group C" ,
                      value: 18.451534877007
                  } ,
                  {
                      label: "Group D" ,
                      value: 8.6142352811805
                  } ,
                  {
                      label: "Group E" ,
                      value: 7.8082472075876
                  } ,
                  {
                      label: "Group F" ,
                      value: 5.259101026956
                  } ,
                  {
                      label: "Group G" ,
                      value: 7.0947953487127
                  } ,
                  {
                      label: "Group H" ,
                      value: 8
                  } ,
                  {
                      label: "Group I" ,
                      value: 21
                  }
              ]
          },
          {
              key: 'Series3',
              values: [
                  {
                      label: "Group A" ,
                      value: -14.307646510375
                  } ,
                  {
                      label: "Group B" ,
                      value: 16.756779544553
                  } ,
                  {
                      label: "Group C" ,
                      value: -18.451534877007
                  } ,
                  {
                      label: "Group D" ,
                      value: 8.6142352811805
                  } ,
                  {
                      label: "Group E" ,
                      value: -7.8082472075876
                  } ,
                  {
                      label: "Group F" ,
                      value: 15.259101026956
                  } ,
                  {
                      label: "Group G" ,
                      value: -0.30947953487127
                  } ,
                  {
                      label: "Group H" ,
                      value: 0
                  } ,
                  {
                      label: "Group I" ,
                      value: 0
                  }
              ]
          }
      ].to_json

    @discete_bar_array = [
          {
              key: "Cumulative Return",
              values: [
                  {
                      label: "A" ,
                      value: 29.765957771107
                  } ,
                  {
                      label: "B" ,
                      value: 0
                  } ,
                  {
                      label: "C" ,
                      value: 32.807804682612
                  } ,
                  {
                      label: "D" ,
                      value: 196.45946739256
                  } ,
                  {
                      label: "E" ,
                      value: 0.19434030906893
                  } ,
                  {
                      label: "F" ,
                      value: -98.079782601442
                  } ,
                  {
                      label: "G" ,
                      value: 13.925743130903
                  } ,
                  {
                      label: "H" ,
                      value: 5.1387322875705
                  }
              ]
          }
      ].to_json

    @data_array_for_boxplot = [
          {
            label: "Sample A",
            values: {
              Q1: 120,
              Q2: 150,
              Q3: 200,
              whisker_low: 115,
              whisker_high: 210,
              outliers: [50, 100, 225]
            },
          },
          {
            label: "Sample B",
            values: {
              Q1: 300,
              Q2: 350,
              Q3: 400,
              whisker_low: 225,
              whisker_high: 425,
              outliers: [175]
            },
          },
          {
            label: "Sample C",
            values: {
              Q1: 50,
              Q2: 100,
              Q3: 125,
              whisker_low: 25,
              whisker_high: 175,
              outliers: [0]
            },
          }
        ].to_json

    @bar_size = {
      height: 300,
      width: 300
    }
    @discrete_bar_size = {
      height: 500,
      width: 500
    }
    @size1 = {
      height: 500,
      width: 500
    }

    @data = {
      :labels => ["January","February","March","April","May","June","July"],
      :datasets => [{
        :label =>"My First dataset",
        :fillColor => "rgba(151,187,205,0.2)",
        :strokeColor => "rgba(151,187,205,1)",
        :highlightFill => "rgba(220,220,220,1)",
        :highlightStroke => "#fff",
        :data => [randomScalingFactor(), randomScalingFactor(), randomScalingFactor(), randomScalingFactor(), randomScalingFactor(), randomScalingFactor(), randomScalingFactor()]
      },
      {
        :label =>"My First dataset",
        :fillColor => "rgba(151,187,205,0.2)",
        :strokeColor => "rgba(151,187,205,1)",
        :highlightFill => "rgba(220,220,220,1)",
        :highlightStroke => "#fff",
        :data => [randomScalingFactor(), randomScalingFactor(), randomScalingFactor(), randomScalingFactor(), randomScalingFactor(), randomScalingFactor(), randomScalingFactor()]
      }]
    }.to_json

    @data2 = {
      :labels => ["January","February","March","April","May","June","July"],
      :datasets => [{
        :label =>"My First dataset",
        :fillColor => "rgba(151,187,205,0.2)",
        :strokeColor => "rgba(151,187,205,1)",
        :highlightFill => "rgba(220,220,220,1)",
        :highlightStroke => "#fff",
        :data => [randomScalingFactor(), randomScalingFactor(), randomScalingFactor(), randomScalingFactor(), randomScalingFactor(), randomScalingFactor(), randomScalingFactor()]
      },
      {
        :label =>"My First dataset",
        :fillColor => "rgba(151,187,205,0.2)",
        :strokeColor => "rgba(151,187,205,1)",
        :highlightFill => "rgba(220,220,220,1)",
        :highlightStroke => "#fff",
        :data => [randomScalingFactor(), randomScalingFactor(), randomScalingFactor(), randomScalingFactor(), randomScalingFactor(), randomScalingFactor(), randomScalingFactor()]
      }]
    }.to_json


    @data3 = {
      :labels => ["January","February","March","April","May","June","July"],
      :datasets => [{
        :label =>"My First dataset",
        :fillColor => "rgba(151,187,205,0.2)",
        :strokeColor => "rgba(151,187,205,1)",
        :highlightFill => "rgba(220,220,220,1)",
        :highlightStroke => "#fff",
        :data => [randomScalingFactor(), randomScalingFactor(), randomScalingFactor(), randomScalingFactor(), randomScalingFactor(), randomScalingFactor(), randomScalingFactor()]
      },
      {
        :label =>"My First dataset",
        :fillColor => "rgba(151,187,205,0.2)",
        :strokeColor => "rgba(151,187,205,1)",
        :highlightFill => "rgba(220,220,220,1)",
        :highlightStroke => "#fff",
        :data => [randomScalingFactor(), randomScalingFactor(), randomScalingFactor(), randomScalingFactor(), randomScalingFactor(), randomScalingFactor(), randomScalingFactor()]
      }]
    }.to_json


    @lineSize = {
      height: 200,
      width: 200
    }


    @lineData = {
        labels: ["January","February","March","April","May","June","July"],
        datasets: [
          {
            label: "My First dataset",
            fillColor: "rgba(220,220,220,0.2)",
            strokeColor: "rgba(220,220,220,1)",
            pointColor: "rgba(220,220,220,1)",
            pointStrokeColor: "#fff",
            pointHighlightFill: "#fff",
            pointHighlightStroke: "rgba(220,220,220,1)",
            data: [randomScalingFactor(),randomScalingFactor(),randomScalingFactor(),randomScalingFactor(),randomScalingFactor(),randomScalingFactor(),randomScalingFactor()]
          },
          {
            label: "My Second dataset",
            fillColor: "rgba(151,187,205,0.2)",
            strokeColor: "rgba(151,187,205,1)",
            pointColor: "rgba(151,187,205,1)",
            pointStrokeColor: "#fff",
            pointHighlightFill: "#fff",
            pointHighlightStroke: "rgba(151,187,205,1)",

app/helpers/front_pages_helper.rb
module FrontPagesHelper
end

app/views/front_pages/_form.html.erb
<%= form_for(@front_page) do |f| %>
  <% if @front_page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@front_page.errors.count, "error") %> prohibited this front_page from being saved:</h2>

      <ul>
      <% @front_page.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/front_pages/edit.html.erb
<h1>Editing Front Page</h1>

<%= render 'form' %>

<%= link_to 'Show', @front_page %> |
<%= link_to 'Back', front_pages_path %>

app/views/front_pages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Front Pages</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @front_pages.each do |front_page| %>
      <tr>
        <td><%= link_to 'Show', front_page %></td>
        <td><%= link_to 'Edit', edit_front_page_path(front_page) %></td>
        <td><%= link_to 'Destroy', front_page, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Front page', new_front_page_path %>

app/views/front_pages/main.html.erb
<style media="screen">
  .float_left {
    float:left;
  }
</style>
<br><br><br><br>

<div class="ribbon right red">
  <a href="http://github.com/ytbryan/chart">Fork me on GitHub</a>
</div>

<div class="center">
  <div class="">
    <span>
      <%= pie :pie_id_2, @pieSize, @pieData %>
      <%= radar :radar_id_2, @radarSize, @radarData %>
    </span>

    <span class="float_left">
      <%= horizontal_grouped_bar "horizontal_grouped_bar2", @size1, @horizontal_grouped_bar_array%>
    </span>
    <span class="float_left">
      <%= discrete_bar "first_discrete_bar2" , @size1, @discete_bar_array %>
    </span>
  </div>

  <br><br><br><br>
  <br><br><br><br>
  <br><br><br><br>
  <br><br><br><br>
  <br><br><br><br>
  <h1 style="text-align:center;">Chart</h1>

  <p>
    Add <span>
      gem 'chart'
    </span> to Gemfile.
  </p>
  <pre class="brush: ruby">
    gem 'chart'
  </pre>

  <p>
    Add specific javascript <span>
      gem 'chart'
    </span> to application.js.
  </p>

  <pre class="brush: ruby">
    //= require turbolinks
    //= require chart
    //= require nvd3
  </pre>

  <p>
    Add css for nvd3 to application.css.
  </p>

  <pre class="brush: ruby">
    *= require nvd3
  </pre>

  <h1 style="text-align:center;">Examples</h1>

  <%= horizontal_grouped_bar "horizontal_grouped_bar", @size1, @horizontal_grouped_bar_array%>

  <pre class="brush: ruby">
    // horizontal_grouped_bar <%# horizontal_grouped_bar "horizontal_grouped_bar", @size1 %>
  </pre>

  <%= discrete_bar "first_discrete_bar" , @discrete_bar_size, @discete_bar_array %>

  <pre class="brush: ruby">
    // discrete_bar
  </pre>

  <%= boxplot "boxplot", @size1, @data_array_for_boxplot %>

  <pre class="brush: ruby">
    // boxplot
  </pre>

  <div class="">
    <%= bar "something", @bar_size, @data %>
    <%= bar "somethingelse", @bar_size,  @data2 %>
    <%= bar "somethingelse2", @bar_size,  @data3 %>
  </div>

  <pre class="brush: ruby">
    // simple bar chart
  </pre>


  <div class="">
    <%= line "line_id", @lineSize, @lineData %>
    <%= line "line_id2", @lineSize, @lineData %>
    <%= line "line_id3", @lineSize, @lineData %>
  </div>

  <pre class="brush: ruby">
    // simple line chart
  </pre>


  <div class="">
    <%= pie :pie_id, @pieSize, @pieData %>
  </div>

  <pre class="brush: ruby">
    // simple line chart
  </pre>


  <div class="">

    <%= radar "radar_id", @radarSize, @radarData %>
  </div>

  <pre class="brush: ruby">
    // simple line chart
  </pre>


</div>

app/views/front_pages/new.html.erb
<h1>New Front Page</h1>

<%= render 'form' %>

<%= link_to 'Back', front_pages_path %>

app/views/front_pages/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_front_page_path(@front_page) %> |
<%= link_to 'Back', front_pages_path %>